import type { Part } from './types';

export const CATALOGUE: Part[] = [
  // ── Servos ─────────────────────────────────────────────────────────────────
  {
    sku: 'FEETECH_STS3215',
    name: 'Feetech STS3215 Serial Bus Servo',
    category: 'servo',
    description: '30 kg.cm serial bus servo. Daisy-chainable via TTL serial. Popular for LeRobot arms.',
    tags: ['servo', 'low-cost', 'serial', 'daisy-chain', 'arm', 'lerobot', 'high-torque'],
    supplier: 'Feetech / 1688',
    price_usd: 14.50,
    lead_time_days: 10,
    mesh_url: 'stl/feetech_sts3215.stl',
    cad_url: null,
    specs: { weight_g: 60, torque_nm: 2.94, voltage_v: 7.4, protocol: 'serial_ttl', max_rpm: 50, dims_mm: [40, 20, 40] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'horn', position: [0, 0, 40], orientation: [0, 0, 0, 1], connector: 'servo_horn_25T', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-180, 180] },
    ],
  },
  {
    sku: 'FEETECH_SCS0009',
    name: 'Feetech SCS0009 Mini Serial Servo',
    category: 'servo',
    description: '1.5 kg.cm lightweight mini servo for wrist and finger joints. TTL serial bus.',
    tags: ['servo', 'mini', 'small', 'wrist', 'finger', 'low-cost', 'serial'],
    supplier: 'Feetech / 1688',
    price_usd: 5.00,
    lead_time_days: 10,
    mesh_url: 'stl/feetech_scs0009.stl',
    cad_url: null,
    specs: { weight_g: 12, torque_nm: 0.15, voltage_v: 5.0, protocol: 'serial_ttl', max_rpm: 60, dims_mm: [23, 12, 24] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'horn', position: [0, 0, 24], orientation: [0, 0, 0, 1], connector: 'servo_horn_20T', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-90, 90] },
    ],
  },
  {
    sku: 'DYNAMIXEL_XL330',
    name: 'Dynamixel XL330-M288',
    category: 'servo',
    description: '0.52 N.m smart servo with magnetic absolute encoder. USB or TTL. Very lightweight.',
    tags: ['servo', 'dynamixel', 'smart', 'usb', 'ttl', 'lightweight', 'arm'],
    supplier: 'Robotis',
    price_usd: 24.90,
    lead_time_days: 5,
    mesh_url: 'stl/dynamixel_xl330.stl',
    cad_url: null,
    specs: { weight_g: 18, torque_nm: 0.52, voltage_v: 5.0, protocol: 'serial_ttl', max_rpm: 130, dims_mm: [20, 34, 26] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'horn', position: [0, 0, 26], orientation: [0, 0, 0, 1], connector: 'dynamixel_x_idler', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-180, 180] },
    ],
  },
  {
    sku: 'WAVESHARE_ST3020',
    name: 'Waveshare ST3020 High-Torque Servo',
    category: 'servo',
    description: '30 kg.cm high-torque TTL servo. Good for shoulder and elbow joints in larger arms.',
    tags: ['servo', 'high-torque', 'ttl', 'waveshare', 'shoulder', 'elbow'],
    supplier: 'Waveshare',
    price_usd: 22.00,
    lead_time_days: 8,
    mesh_url: 'stl/waveshare_st3020.stl',
    cad_url: null,
    specs: { weight_g: 65, torque_nm: 2.94, voltage_v: 7.4, protocol: 'serial_ttl', max_rpm: 45, dims_mm: [40, 20, 40] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'horn', position: [0, 0, 40], orientation: [0, 0, 0, 1], connector: 'servo_horn_25T', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-180, 180] },
    ],
  },

  // ── Brackets ───────────────────────────────────────────────────────────────
  {
    sku: 'BRACKET_U_SMALL',
    name: 'Small U-Bracket (aluminum)',
    category: 'bracket',
    description: 'Small U-shaped bracket for joining two STS3215-class servos in series. 20x20 mounting pattern.',
    tags: ['bracket', 'u-bracket', 'aluminum', 'arm'],
    supplier: '1688 generic',
    price_usd: 3.20,
    lead_time_days: 7,
    mesh_url: 'stl/bracket_u_small.stl',
    cad_url: 'step/bracket_u_small.step',
    specs: { weight_g: 18, material: '6061 aluminum', dims_mm: [40, 40, 25] },
    mount_points: [
      { id: 'input', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'servo_horn_25T', is_joint: false },
      { id: 'output', position: [0, 0, 40], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
    ],
  },
  {
    sku: 'BRACKET_U_LARGE',
    name: 'Large U-Bracket (aluminum)',
    category: 'bracket',
    description: 'Large U-bracket for heavier servos. 30x30mm mounting pattern. For upper-arm joints.',
    tags: ['bracket', 'u-bracket', 'aluminum', 'large', 'arm'],
    supplier: '1688 generic',
    price_usd: 4.80,
    lead_time_days: 7,
    mesh_url: 'stl/bracket_u_large.stl',
    cad_url: null,
    specs: { weight_g: 32, material: '6061 aluminum', dims_mm: [60, 60, 35] },
    mount_points: [
      { id: 'input', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'servo_horn_25T', is_joint: false },
      { id: 'output', position: [0, 0, 55], orientation: [0, 0, 0, 1], connector: 'm3_4hole_30x30', is_joint: false },
    ],
  },
  {
    sku: 'BRACKET_L_MEDIUM',
    name: 'L-Bracket 40mm (aluminum)',
    category: 'bracket',
    description: '90° L-bracket for perpendicular servo attachment. 20x20mm bolt pattern on both faces.',
    tags: ['bracket', 'l-bracket', 'aluminum', 'perpendicular'],
    supplier: '1688 generic',
    price_usd: 2.50,
    lead_time_days: 7,
    mesh_url: 'stl/bracket_l_medium.stl',
    cad_url: null,
    specs: { weight_g: 14, material: '6061 aluminum', dims_mm: [40, 40, 20] },
    mount_points: [
      { id: 'face_a', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'face_b', position: [40, 0, 20], orientation: [0, 0, 0.707, 0.707], connector: 'm3_4hole_20x20', is_joint: false },
    ],
  },

  // ── Frames ─────────────────────────────────────────────────────────────────
  {
    sku: 'FRAME_EXTRUSION_200',
    name: '2020 Aluminum Extrusion 200mm',
    category: 'frame',
    description: 'V-slot 20×20mm aluminum extrusion, 200mm long. Rigid structural link for robot arms and frames.',
    tags: ['frame', 'extrusion', '2020', 'aluminum', 'structural'],
    supplier: '1688 generic',
    price_usd: 4.00,
    lead_time_days: 5,
    mesh_url: 'stl/extrusion_2020_200.stl',
    cad_url: null,
    specs: { weight_g: 65, material: '6063 aluminum', dims_mm: [20, 20, 200] },
    mount_points: [
      { id: 'end_a', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'extrusion_2020_end', is_joint: false },
      { id: 'end_b', position: [0, 0, 200], orientation: [0, 0, 1, 0], connector: 'extrusion_2020_end', is_joint: false },
    ],
  },
  {
    sku: 'FRAME_BASE_PLATE',
    name: 'Robot Base Plate 100×100mm',
    category: 'frame',
    description: 'Flat 3mm aluminum base plate. M3 holes on 30×30mm grid. Mounts the first servo of a desktop arm.',
    tags: ['frame', 'base', 'plate', 'mounting', 'desktop'],
    supplier: '1688 generic',
    price_usd: 6.00,
    lead_time_days: 7,
    mesh_url: 'stl/base_plate_100.stl',
    cad_url: null,
    specs: { weight_g: 80, material: '6061 aluminum', dims_mm: [100, 100, 3] },
    mount_points: [
      { id: 'servo_mount', position: [50, 50, 3], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
    ],
  },

  // ── Controllers ────────────────────────────────────────────────────────────
  {
    sku: 'WAVESHARE_ESP32_S3',
    name: 'Waveshare ESP32-S3 Dev Board',
    category: 'controller',
    description: 'ESP32-S3 development board with USB-C. Controls up to 8 serial servos via TTL UART. WiFi + BLE onboard.',
    tags: ['controller', 'esp32', 'wifi', 'ble', 'usb', 'micro', 'serial'],
    supplier: 'Waveshare',
    price_usd: 12.00,
    lead_time_days: 7,
    mesh_url: 'stl/esp32_s3_dev.stl',
    cad_url: null,
    specs: { weight_g: 15, ports: ['uart0', 'uart1', 'i2c', 'spi', 'usb-c'], power_w: 1.5, dims_mm: [65, 30, 10] },
    mount_points: [
      { id: 'board_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'controller_mount_esp32_devkit', is_joint: false },
    ],
  },
  {
    sku: 'RASPBERRY_PI_ZERO_2W',
    name: 'Raspberry Pi Zero 2W',
    category: 'controller',
    description: 'Quad-core ARM Cortex-A53, 512MB RAM. Runs ROS2. For vision-enabled robots and ML inference.',
    tags: ['controller', 'raspberry-pi', 'linux', 'ros2', 'vision', 'wifi'],
    supplier: 'Raspberry Pi Foundation',
    price_usd: 15.00,
    lead_time_days: 14,
    mesh_url: 'stl/rpi_zero_2w.stl',
    cad_url: null,
    specs: { weight_g: 10, ports: ['usb-micro', 'csi', 'hdmi-mini', 'gpio-40pin'], power_w: 2.0, dims_mm: [65, 30, 5] },
    mount_points: [
      { id: 'board_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'controller_mount_pi', is_joint: false },
    ],
  },

  // ── Battery ────────────────────────────────────────────────────────────────
  {
    sku: 'LIPO_2S_1200MAH',
    name: 'LiPo 2S 1200mAh (7.4V)',
    category: 'battery',
    description: '7.4V 2S LiPo battery. Powers 4–6 Feetech servos for ~45 min of active use. XT30 connector.',
    tags: ['battery', 'lipo', '7.4v', '2s', 'xt30', 'arm'],
    supplier: 'Turnigy / HobbyKing',
    price_usd: 8.50,
    lead_time_days: 10,
    mesh_url: 'stl/lipo_2s_1200.stl',
    cad_url: null,
    specs: { weight_g: 72, voltage_v: 7.4, capacity_mah: 1200, connector: 'XT30', dims_mm: [68, 35, 14] },
    mount_points: [
      { id: 'body_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_30x30', is_joint: false },
    ],
  },

  // ── Gripper ─────────────────────────────────────────────────────────────────
  {
    sku: 'GRIPPER_PARALLEL_MINI',
    name: 'Mini Parallel Gripper',
    category: 'gripper',
    description: 'Two-finger parallel gripper driven by one SCS0009 servo. 30mm stroke, 200g payload. Includes mounting bracket.',
    tags: ['gripper', 'parallel', 'two-finger', 'mini', 'end-effector'],
    supplier: '1688 generic',
    price_usd: 18.00,
    lead_time_days: 12,
    mesh_url: 'stl/gripper_parallel_mini.stl',
    cad_url: null,
    specs: { weight_g: 45, max_payload_g: 200, stroke_mm: 30, dims_mm: [50, 40, 60] },
    mount_points: [
      { id: 'servo_input', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'servo_horn_20T', is_joint: false },
      { id: 'wrist_mount', position: [0, 0, 60], orientation: [0, 0, 1, 0], connector: 'm3_4hole_20x20', is_joint: false },
    ],
  },

  // ── Additional Servos ───────────────────────────────────────────────────────
  {
    sku: 'FEETECH_STS3032',
    name: 'Feetech STS3032 Serial Bus Servo',
    category: 'servo',
    description: '30 kg.cm serial bus servo at 12V. Same 25T horn and footprint as STS3215. Good for 12V systems.',
    tags: ['servo', 'feetech', 'serial', 'ttl', 'daisy-chain', 'arm', '12v'],
    supplier: 'Feetech / 1688',
    price_usd: 16.00,
    lead_time_days: 10,
    mesh_url: 'stl/feetech_sts3215.stl',
    cad_url: null,
    specs: { weight_g: 60, torque_nm: 2.94, voltage_v: 12.0, protocol: 'serial_ttl', max_rpm: 50, dims_mm: [40, 20, 40] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'horn', position: [0, 0, 40], orientation: [0, 0, 0, 1], connector: 'servo_horn_25T', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-180, 180] },
    ],
  },
  {
    sku: 'FEETECH_SCS0215',
    name: 'Feetech SCS0215 Serial Bus Servo',
    category: 'servo',
    description: '15 kg.cm mid-range SCS servo at 6V. 25T horn, 20×20 bolt pattern. Great for compact arms.',
    tags: ['servo', 'feetech', 'serial', 'scs', 'ttl', 'mid-range', 'arm', '6v'],
    supplier: 'Feetech / 1688',
    price_usd: 10.00,
    lead_time_days: 10,
    mesh_url: 'stl/feetech_sts3215.stl',
    cad_url: null,
    specs: { weight_g: 55, torque_nm: 1.47, voltage_v: 6.0, protocol: 'serial_ttl', max_rpm: 60, dims_mm: [40, 20, 40] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'horn', position: [0, 0, 40], orientation: [0, 0, 0, 1], connector: 'servo_horn_25T', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-180, 180] },
    ],
  },
  {
    sku: 'FEETECH_STS4215',
    name: 'Feetech STS4215 High-Torque Servo',
    category: 'servo',
    description: '40 kg.cm serial bus servo, 12V. Metal gears, same 25T horn. For heavy shoulder/base joints.',
    tags: ['servo', 'feetech', 'high-torque', 'serial', 'ttl', 'heavy-duty', 'shoulder', 'base', '12v'],
    supplier: 'Feetech / 1688',
    price_usd: 22.00,
    lead_time_days: 10,
    mesh_url: 'stl/feetech_sts3215.stl',
    cad_url: null,
    specs: { weight_g: 65, torque_nm: 3.92, voltage_v: 12.0, protocol: 'serial_ttl', max_rpm: 40, dims_mm: [40, 20, 40] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'horn', position: [0, 0, 40], orientation: [0, 0, 0, 1], connector: 'servo_horn_25T', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-180, 180] },
    ],
  },
  {
    sku: 'DYNAMIXEL_XL430',
    name: 'Dynamixel XL430-W250',
    category: 'servo',
    description: '1.4 N.m smart servo, 12V, TTL/RS485. Position/velocity/torque control, accurate absolute encoder. Popular for medium arms.',
    tags: ['servo', 'dynamixel', 'smart', 'ttl', 'medium', 'arm', 'ros2', '12v'],
    supplier: 'Robotis',
    price_usd: 49.90,
    lead_time_days: 5,
    mesh_url: 'stl/dynamixel_xl330.stl',
    cad_url: null,
    specs: { weight_g: 57, torque_nm: 1.4, voltage_v: 12.0, protocol: 'serial_ttl', max_rpm: 61, dims_mm: [28, 47, 34] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_30x30', is_joint: false },
      { id: 'horn', position: [0, 0, 34], orientation: [0, 0, 0, 1], connector: 'dynamixel_x_idler', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-180, 180] },
    ],
  },
  {
    sku: 'DYNAMIXEL_XC330',
    name: 'Dynamixel XC330-T288',
    category: 'servo',
    description: '0.76 N.m compact smart servo, 5–24V input. TTL. Lighter XL330 alternative with higher voltage range.',
    tags: ['servo', 'dynamixel', 'compact', 'smart', 'ttl', 'lightweight', 'arm', '24v'],
    supplier: 'Robotis',
    price_usd: 49.90,
    lead_time_days: 5,
    mesh_url: 'stl/dynamixel_xl330.stl',
    cad_url: null,
    specs: { weight_g: 22, torque_nm: 0.76, voltage_v: 12.0, protocol: 'serial_ttl', max_rpm: 120, dims_mm: [20, 34, 26] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'horn', position: [0, 0, 26], orientation: [0, 0, 0, 1], connector: 'dynamixel_x_idler', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-180, 180] },
    ],
  },
  {
    sku: 'DYNAMIXEL_MX28',
    name: 'Dynamixel MX-28T',
    category: 'servo',
    description: '2.5 N.m high-torque smart servo, 12V, TTL. Magnetic encoder, full 360° position. For heavy articulated arms.',
    tags: ['servo', 'dynamixel', 'high-torque', 'smart', 'ttl', 'arm', 'heavy-duty', '12v'],
    supplier: 'Robotis',
    price_usd: 215.00,
    lead_time_days: 5,
    mesh_url: 'stl/dynamixel_xl330.stl',
    cad_url: null,
    specs: { weight_g: 72, torque_nm: 2.5, voltage_v: 12.0, protocol: 'serial_ttl', max_rpm: 55, dims_mm: [36, 51, 36] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_30x30', is_joint: false },
      { id: 'horn', position: [0, 0, 36], orientation: [0, 0, 0, 1], connector: 'dynamixel_x_idler', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-180, 180] },
    ],
  },
  {
    sku: 'SERVO_MG996R',
    name: 'MG996R Metal Gear Servo',
    category: 'servo',
    description: 'Budget 10 kg.cm metal-gear hobby servo. PWM control. Great for low-cost pan-tilt or simple joint actuators.',
    tags: ['servo', 'hobby', 'budget', 'pwm', 'metal-gear', 'pan-tilt', 'analog'],
    supplier: 'Generic / Aliexpress',
    price_usd: 3.50,
    lead_time_days: 12,
    mesh_url: 'stl/feetech_sts3215.stl',
    cad_url: null,
    specs: { weight_g: 55, torque_nm: 0.98, voltage_v: 6.0, protocol: 'pwm', max_rpm: 60, dims_mm: [40, 20, 38] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'horn', position: [0, 0, 38], orientation: [0, 0, 0, 1], connector: 'servo_horn_25T', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-90, 90] },
    ],
  },
  {
    sku: 'SERVO_DS3218',
    name: 'DS3218 20kg Digital Servo',
    category: 'servo',
    description: '20 kg.cm metal-gear digital servo. PWM/PPM. Good mid-range option for arms under $200 BOM.',
    tags: ['servo', 'hobby', 'budget', 'digital', 'pwm', 'metal-gear', '20kg', 'arm'],
    supplier: 'Generic / Aliexpress',
    price_usd: 7.50,
    lead_time_days: 12,
    mesh_url: 'stl/feetech_sts3215.stl',
    cad_url: null,
    specs: { weight_g: 60, torque_nm: 1.96, voltage_v: 7.4, protocol: 'pwm', max_rpm: 50, dims_mm: [40, 20, 40] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'horn', position: [0, 0, 40], orientation: [0, 0, 0, 1], connector: 'servo_horn_25T', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-120, 120] },
    ],
  },
  {
    sku: 'HITEC_HS645MG',
    name: 'Hitec HS-645MG Metal Gear Servo',
    category: 'servo',
    description: '9.6 kg.cm analog servo, metal gears, karbonite gears. PWM. Industry-standard hobby servo for precision builds.',
    tags: ['servo', 'hitec', 'hobby', 'analog', 'pwm', 'metal-gear', 'precision'],
    supplier: 'Hitec',
    price_usd: 22.00,
    lead_time_days: 7,
    mesh_url: 'stl/feetech_sts3215.stl',
    cad_url: null,
    specs: { weight_g: 55, torque_nm: 0.94, voltage_v: 6.0, protocol: 'pwm', max_rpm: 62, dims_mm: [41, 20, 37] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'horn', position: [0, 0, 37], orientation: [0, 0, 0, 1], connector: 'servo_horn_25T', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-90, 90] },
    ],
  },
  {
    sku: 'GOBILDA_SERVO_2000',
    name: 'goBILDA 2000 Series Dual Mode Servo',
    category: 'servo',
    description: '13.5 kg.cm servo with PWM and goBILDA M4-grid compatible output shaft. Designed for goBILDA structural systems.',
    tags: ['servo', 'gobilda', 'dual-mode', 'pwm', 'structural', 'ftc', 'robotics'],
    supplier: 'goBILDA',
    price_usd: 34.99,
    lead_time_days: 5,
    mesh_url: 'stl/feetech_sts3215.stl',
    cad_url: null,
    specs: { weight_g: 62, torque_nm: 1.32, voltage_v: 6.0, protocol: 'pwm', max_rpm: 55, dims_mm: [46, 24, 38] },
    mount_points: [
      { id: 'base', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'gobilda_m4_8mm', is_joint: false },
      { id: 'horn', position: [0, 0, 38], orientation: [0, 0, 0, 1], connector: 'servo_horn_25T', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-300, 300] },
    ],
  },

  // ── goBILDA Structural ─────────────────────────────────────────────────────
  {
    sku: 'GOBILDA_U_CHANNEL_2',
    name: 'goBILDA 1120 U-Channel 2-Hole (72mm)',
    category: 'bracket',
    description: 'Aluminum U-channel 72mm long. M4 holes on 8mm grid. Connects two goBILDA structural elements.',
    tags: ['bracket', 'gobilda', 'u-channel', 'structural', 'aluminum', 'ftc', '2-hole', '72mm'],
    supplier: 'goBILDA',
    price_usd: 7.49,
    lead_time_days: 5,
    mesh_url: 'stl/bracket_u_small.stl',
    cad_url: null,
    specs: { weight_g: 28, material: '6061 aluminum', dims_mm: [72, 24, 24] },
    mount_points: [
      { id: 'face_a', position: [0, 12, 12], orientation: [0, 0, 0, 1], connector: 'gobilda_m4_8mm', is_joint: false },
      { id: 'face_b', position: [72, 12, 12], orientation: [0, 0, 1, 0], connector: 'gobilda_m4_8mm', is_joint: false },
      { id: 'servo_mount', position: [36, 24, 12], orientation: [0.707, 0, 0, 0.707], connector: 'servo_horn_25T', is_joint: false },
    ],
  },
  {
    sku: 'GOBILDA_U_CHANNEL_5',
    name: 'goBILDA 1120 U-Channel 5-Hole (168mm)',
    category: 'bracket',
    description: 'Aluminum U-channel 168mm long. M4 holes on 8mm grid. Standard structural link for FTC and hobby robots.',
    tags: ['bracket', 'gobilda', 'u-channel', 'structural', 'aluminum', 'ftc', '5-hole', '168mm'],
    supplier: 'goBILDA',
    price_usd: 11.49,
    lead_time_days: 5,
    mesh_url: 'stl/bracket_u_large.stl',
    cad_url: null,
    specs: { weight_g: 55, material: '6061 aluminum', dims_mm: [168, 24, 24] },
    mount_points: [
      { id: 'face_a', position: [0, 12, 12], orientation: [0, 0, 0, 1], connector: 'gobilda_m4_8mm', is_joint: false },
      { id: 'face_b', position: [168, 12, 12], orientation: [0, 0, 1, 0], connector: 'gobilda_m4_8mm', is_joint: false },
      { id: 'servo_mount', position: [84, 24, 12], orientation: [0.707, 0, 0, 0.707], connector: 'servo_horn_25T', is_joint: false },
    ],
  },
  {
    sku: 'GOBILDA_U_CHANNEL_9',
    name: 'goBILDA 1120 U-Channel 9-Hole (336mm)',
    category: 'bracket',
    description: 'Long aluminum U-channel 336mm. Good for forearm links in larger robot arms or mobile robot framing.',
    tags: ['bracket', 'gobilda', 'u-channel', 'structural', 'aluminum', 'long', 'forearm', '336mm'],
    supplier: 'goBILDA',
    price_usd: 16.49,
    lead_time_days: 5,
    mesh_url: 'stl/bracket_u_large.stl',
    cad_url: null,
    specs: { weight_g: 98, material: '6061 aluminum', dims_mm: [336, 24, 24] },
    mount_points: [
      { id: 'face_a', position: [0, 12, 12], orientation: [0, 0, 0, 1], connector: 'gobilda_m4_8mm', is_joint: false },
      { id: 'face_b', position: [336, 12, 12], orientation: [0, 0, 1, 0], connector: 'gobilda_m4_8mm', is_joint: false },
    ],
  },
  {
    sku: 'GOBILDA_FLAT_BRACKET_1x2',
    name: 'goBILDA 1100 Flat Bracket 1×2',
    category: 'bracket',
    description: 'Flat aluminum bracket 28×56mm, M4 holes on 8mm grid. Used to connect two goBILDA beams at 90° or inline.',
    tags: ['bracket', 'gobilda', 'flat', 'aluminum', 'ftc', '1x2'],
    supplier: 'goBILDA',
    price_usd: 3.49,
    lead_time_days: 5,
    mesh_url: 'stl/bracket_l_medium.stl',
    cad_url: null,
    specs: { weight_g: 7, material: '6061 aluminum', dims_mm: [56, 28, 3] },
    mount_points: [
      { id: 'face_a', position: [0, 14, 0], orientation: [0, 0, 0, 1], connector: 'gobilda_m4_8mm', is_joint: false },
      { id: 'face_b', position: [56, 14, 0], orientation: [0, 0, 1, 0], connector: 'gobilda_m4_8mm', is_joint: false },
    ],
  },
  {
    sku: 'GOBILDA_FLAT_BRACKET_2x3',
    name: 'goBILDA 1100 Flat Bracket 2×3',
    category: 'bracket',
    description: 'Flat aluminum bracket 56×80mm, M4 holes on 8mm grid. Stiffer and larger than 1×2, good for base or mid-robot framing.',
    tags: ['bracket', 'gobilda', 'flat', 'aluminum', 'ftc', '2x3', 'base'],
    supplier: 'goBILDA',
    price_usd: 4.49,
    lead_time_days: 5,
    mesh_url: 'stl/bracket_u_small.stl',
    cad_url: null,
    specs: { weight_g: 14, material: '6061 aluminum', dims_mm: [80, 56, 3] },
    mount_points: [
      { id: 'face_a', position: [0, 28, 0], orientation: [0, 0, 0, 1], connector: 'gobilda_m4_8mm', is_joint: false },
      { id: 'face_b', position: [80, 28, 0], orientation: [0, 0, 1, 0], connector: 'gobilda_m4_8mm', is_joint: false },
    ],
  },
  {
    sku: 'GOBILDA_QUAD_BLOCK',
    name: 'goBILDA 1300 Quad Block',
    category: 'bracket',
    description: '24mm cubic block with M4 grid on all 4 sides. Hub for connecting four beams or channels at 90° angles.',
    tags: ['bracket', 'gobilda', 'hub', 'quad', 'block', 'junction', 'ftc'],
    supplier: 'goBILDA',
    price_usd: 5.99,
    lead_time_days: 5,
    mesh_url: 'stl/bracket_u_small.stl',
    cad_url: null,
    specs: { weight_g: 12, material: '6061 aluminum', dims_mm: [24, 24, 24] },
    mount_points: [
      { id: 'face_a', position: [0, 12, 12], orientation: [0, 0, 0, 1], connector: 'gobilda_m4_8mm', is_joint: false },
      { id: 'face_b', position: [24, 12, 12], orientation: [0, 0, 1, 0], connector: 'gobilda_m4_8mm', is_joint: false },
      { id: 'face_c', position: [12, 0, 12], orientation: [0.707, 0, 0, 0.707], connector: 'gobilda_m4_8mm', is_joint: false },
      { id: 'face_d', position: [12, 24, 12], orientation: [-0.707, 0, 0, 0.707], connector: 'gobilda_m4_8mm', is_joint: false },
    ],
  },
  {
    sku: 'GOBILDA_SERVO_MOUNT_43MM',
    name: 'goBILDA 2000 Servo Bracket 43mm',
    category: 'bracket',
    description: 'Aluminum servo bracket that converts any standard 25T servo horn to a goBILDA M4 grid mount. 43mm spacing.',
    tags: ['bracket', 'gobilda', 'servo-mount', 'adapter', '25t', 'aluminum'],
    supplier: 'goBILDA',
    price_usd: 8.99,
    lead_time_days: 5,
    mesh_url: 'stl/bracket_u_small.stl',
    cad_url: null,
    specs: { weight_g: 22, material: '6061 aluminum', dims_mm: [43, 24, 43] },
    mount_points: [
      { id: 'servo_horn', position: [0, 12, 0], orientation: [0, 0, 0, 1], connector: 'servo_horn_25T', is_joint: false },
      { id: 'output', position: [43, 12, 43], orientation: [0, 0, 1, 0], connector: 'gobilda_m4_8mm', is_joint: false },
    ],
  },
  {
    sku: 'BRACKET_C_MEDIUM',
    name: 'C-Bracket 50mm (aluminum)',
    category: 'bracket',
    description: 'C-shaped bracket for attaching a servo body to a structural link. Two M3 faces at 90°. 50mm arm length.',
    tags: ['bracket', 'c-bracket', 'aluminum', 'servo', 'arm'],
    supplier: '1688 generic',
    price_usd: 3.80,
    lead_time_days: 7,
    mesh_url: 'stl/bracket_l_medium.stl',
    cad_url: null,
    specs: { weight_g: 16, material: '6061 aluminum', dims_mm: [50, 25, 50] },
    mount_points: [
      { id: 'servo_body', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'structure', position: [50, 0, 50], orientation: [0, 0, 0.707, 0.707], connector: 'm3_4hole_20x20', is_joint: false },
    ],
  },

  // ── Additional Frames ───────────────────────────────────────────────────────
  {
    sku: 'FRAME_EXTRUSION_300',
    name: '2020 Aluminum Extrusion 300mm',
    category: 'frame',
    description: 'V-slot 20×20mm aluminum extrusion, 300mm. Common forearm length for desktop robot arms.',
    tags: ['frame', 'extrusion', '2020', 'aluminum', 'structural', '300mm'],
    supplier: '1688 generic',
    price_usd: 5.00,
    lead_time_days: 5,
    mesh_url: 'stl/extrusion_2020_200.stl',
    cad_url: null,
    specs: { weight_g: 97, material: '6063 aluminum', dims_mm: [20, 20, 300] },
    mount_points: [
      { id: 'end_a', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'extrusion_2020_end', is_joint: false },
      { id: 'end_b', position: [0, 0, 300], orientation: [0, 0, 1, 0], connector: 'extrusion_2020_end', is_joint: false },
    ],
  },
  {
    sku: 'FRAME_EXTRUSION_400',
    name: '2020 Aluminum Extrusion 400mm',
    category: 'frame',
    description: 'V-slot 20×20mm aluminum extrusion, 400mm. Used for mobile robot chassis rails and tall structural frames.',
    tags: ['frame', 'extrusion', '2020', 'aluminum', 'structural', '400mm', 'chassis'],
    supplier: '1688 generic',
    price_usd: 6.00,
    lead_time_days: 5,
    mesh_url: 'stl/extrusion_2020_200.stl',
    cad_url: null,
    specs: { weight_g: 130, material: '6063 aluminum', dims_mm: [20, 20, 400] },
    mount_points: [
      { id: 'end_a', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'extrusion_2020_end', is_joint: false },
      { id: 'end_b', position: [0, 0, 400], orientation: [0, 0, 1, 0], connector: 'extrusion_2020_end', is_joint: false },
    ],
  },
  {
    sku: 'FRAME_BASE_PLATE_150',
    name: 'Robot Base Plate 150×150mm',
    category: 'frame',
    description: '3mm aluminum plate with M3 holes on 30mm grid. Larger base for 4-DOF+ arms or dual-arm setups.',
    tags: ['frame', 'base', 'plate', 'mounting', 'desktop', '150mm', 'large'],
    supplier: '1688 generic',
    price_usd: 10.00,
    lead_time_days: 7,
    mesh_url: 'stl/base_plate_100.stl',
    cad_url: null,
    specs: { weight_g: 180, material: '6061 aluminum', dims_mm: [150, 150, 3] },
    mount_points: [
      { id: 'servo_mount_a', position: [75, 75, 3], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'servo_mount_b', position: [75, 45, 3], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
    ],
  },
  {
    sku: 'GOBILDA_STANDOFF_43MM',
    name: 'goBILDA M4 Hex Standoff 43mm',
    category: 'frame',
    description: 'Hex aluminum standoff 43mm, M4 threads. For spacing PCBs, creating layered robot structures.',
    tags: ['frame', 'gobilda', 'standoff', 'spacer', 'm4', '43mm', 'aluminum'],
    supplier: 'goBILDA',
    price_usd: 2.49,
    lead_time_days: 5,
    mesh_url: 'stl/extrusion_2020_200.stl',
    cad_url: null,
    specs: { weight_g: 8, material: '6061 aluminum', dims_mm: [7, 7, 43] },
    mount_points: [
      { id: 'end_a', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'gobilda_m4_8mm', is_joint: false },
      { id: 'end_b', position: [0, 0, 43], orientation: [0, 0, 1, 0], connector: 'gobilda_m4_8mm', is_joint: false },
    ],
  },

  // ── Additional Controllers ──────────────────────────────────────────────────
  {
    sku: 'RASPBERRY_PI_4B',
    name: 'Raspberry Pi 4 Model B (4GB)',
    category: 'controller',
    description: 'Quad-core Cortex-A72, 4GB RAM. Full Linux/ROS2 host. Runs vision models, motion planning. Two USB 3.0 + Gigabit ETH.',
    tags: ['controller', 'raspberry-pi', 'linux', 'ros2', 'vision', 'wifi', 'usb3', 'powerful'],
    supplier: 'Raspberry Pi Foundation',
    price_usd: 55.00,
    lead_time_days: 7,
    mesh_url: 'stl/esp32_s3_dev.stl',
    cad_url: null,
    specs: { weight_g: 46, ports: ['usb-a×4', 'usb-c-power', 'csi', 'hdmi×2', 'gpio-40pin', 'gige'], power_w: 7.5, dims_mm: [85, 56, 17] },
    mount_points: [
      { id: 'board_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'controller_mount_pi', is_joint: false },
    ],
  },
  {
    sku: 'RASPBERRY_PI_5',
    name: 'Raspberry Pi 5 (4GB)',
    category: 'controller',
    description: 'Cortex-A76, 4GB RAM, PCIe. 3× faster than Pi 4. Best choice for real-time vision + inference in a robot.',
    tags: ['controller', 'raspberry-pi', 'linux', 'ros2', 'vision', 'inference', 'powerful', 'pcie'],
    supplier: 'Raspberry Pi Foundation',
    price_usd: 60.00,
    lead_time_days: 7,
    mesh_url: 'stl/esp32_s3_dev.stl',
    cad_url: null,
    specs: { weight_g: 51, ports: ['usb-a×2', 'usb-c×2', 'csi×2', 'hdmi×2', 'gpio-40pin', 'pcie-m2'], power_w: 12.0, dims_mm: [85, 56, 20] },
    mount_points: [
      { id: 'board_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'controller_mount_pi', is_joint: false },
    ],
  },
  {
    sku: 'ARDUINO_MEGA_2560',
    name: 'Arduino Mega 2560 R3',
    category: 'controller',
    description: 'ATmega2560, 16MHz, 54 digital I/O, 4× UART. Good for low-level PWM servo control and sensor fusion. No WiFi.',
    tags: ['controller', 'arduino', 'pwm', 'servo-driver', 'low-level', 'uart', 'budget'],
    supplier: 'Arduino / clone',
    price_usd: 16.00,
    lead_time_days: 7,
    mesh_url: 'stl/esp32_s3_dev.stl',
    cad_url: null,
    specs: { weight_g: 37, ports: ['uart×4', 'spi', 'i2c', 'usb-b', 'gpio-54'], power_w: 0.5, dims_mm: [101, 53, 15] },
    mount_points: [
      { id: 'board_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'controller_mount_arduino', is_joint: false },
    ],
  },
  {
    sku: 'TEENSY_41',
    name: 'Teensy 4.1',
    category: 'controller',
    description: 'Cortex-M7 600MHz, 7× UART, 3× SPI, real-time capable. Best microcontroller for low-latency servo loops and IMU fusion.',
    tags: ['controller', 'teensy', 'real-time', 'microcontroller', 'fast', 'uart', 'servo-driver'],
    supplier: 'PJRC',
    price_usd: 29.85,
    lead_time_days: 7,
    mesh_url: 'stl/esp32_s3_dev.stl',
    cad_url: null,
    specs: { weight_g: 9, ports: ['uart×7', 'spi×3', 'i2c×3', 'usb-c', 'gpio-55', 'ethernet'], power_w: 0.6, dims_mm: [61, 18, 4] },
    mount_points: [
      { id: 'board_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'controller_mount_teensy', is_joint: false },
    ],
  },
  {
    sku: 'DYNAMIXEL_U2D2',
    name: 'Dynamixel U2D2 USB-to-TTL Adapter',
    category: 'controller',
    description: 'USB-to-TTL/RS485 adapter for Dynamixel servos. Required to control Dynamixel chains from PC or SBC via SDK.',
    tags: ['controller', 'dynamixel', 'usb', 'ttl', 'rs485', 'adapter', 'interface'],
    supplier: 'Robotis',
    price_usd: 29.90,
    lead_time_days: 5,
    mesh_url: 'stl/esp32_s3_dev.stl',
    cad_url: null,
    specs: { weight_g: 8, ports: ['usb-micro', 'jst-sh-3pin-ttl', 'jst-sh-3pin-rs485'], power_w: 0.1, dims_mm: [47, 18, 9] },
    mount_points: [
      { id: 'board_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_generic', is_joint: false },
    ],
  },
  {
    sku: 'JETSON_NANO_4GB',
    name: 'NVIDIA Jetson Nano 4GB',
    category: 'controller',
    description: '128-core Maxwell GPU, Quad Cortex-A57, 4GB LPDDR4. Runs inference on-robot. Best for vision+manipulation.',
    tags: ['controller', 'jetson', 'nvidia', 'gpu', 'inference', 'vision', 'ros2', 'linux', 'powerful'],
    supplier: 'NVIDIA',
    price_usd: 149.00,
    lead_time_days: 14,
    mesh_url: 'stl/esp32_s3_dev.stl',
    cad_url: null,
    specs: { weight_g: 140, ports: ['usb-a×4', 'hdmi', 'csi×2', 'gpio-40pin', 'gige', 'pcie'], power_w: 10.0, dims_mm: [100, 79, 28] },
    mount_points: [
      { id: 'board_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'controller_mount_pi', is_joint: false },
    ],
  },

  // ── Additional Batteries ────────────────────────────────────────────────────
  {
    sku: 'LIPO_3S_2200MAH',
    name: 'LiPo 3S 2200mAh (11.1V)',
    category: 'battery',
    description: '11.1V 3S LiPo. Powers 6–8 high-torque servos. XT60 connector. Enough for 30–45 min continuous operation.',
    tags: ['battery', 'lipo', '11.1v', '3s', 'xt60', 'high-power', 'arm', 'mobile'],
    supplier: 'Turnigy / HobbyKing',
    price_usd: 22.00,
    lead_time_days: 10,
    mesh_url: 'stl/lipo_2s_1200.stl',
    cad_url: null,
    specs: { weight_g: 175, voltage_v: 11.1, capacity_mah: 2200, connector: 'XT60', dims_mm: [115, 35, 25] },
    mount_points: [
      { id: 'body_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_30x30', is_joint: false },
    ],
  },
  {
    sku: 'LIPO_4S_5000MAH',
    name: 'LiPo 4S 5000mAh (14.8V)',
    category: 'battery',
    description: '14.8V 4S LiPo for heavy mobile robots and large arms. XT90 connector. Long run time for field use.',
    tags: ['battery', 'lipo', '14.8v', '4s', 'xt90', 'high-capacity', 'mobile', 'heavy'],
    supplier: 'Turnigy / HobbyKing',
    price_usd: 45.00,
    lead_time_days: 10,
    mesh_url: 'stl/lipo_2s_1200.stl',
    cad_url: null,
    specs: { weight_g: 380, voltage_v: 14.8, capacity_mah: 5000, connector: 'XT90', dims_mm: [155, 55, 43] },
    mount_points: [
      { id: 'body_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_30x30', is_joint: false },
    ],
  },
  {
    sku: 'LIPO_2S_3300MAH',
    name: 'LiPo 2S 3300mAh (7.4V)',
    category: 'battery',
    description: '7.4V 2S LiPo with 3300mAh capacity. XT60 connector. Good balance of weight and runtime for desktop arms.',
    tags: ['battery', 'lipo', '7.4v', '2s', 'xt60', 'medium', 'desktop', 'arm'],
    supplier: 'Turnigy / HobbyKing',
    price_usd: 28.00,
    lead_time_days: 10,
    mesh_url: 'stl/lipo_2s_1200.stl',
    cad_url: null,
    specs: { weight_g: 205, voltage_v: 7.4, capacity_mah: 3300, connector: 'XT60', dims_mm: [108, 35, 23] },
    mount_points: [
      { id: 'body_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_30x30', is_joint: false },
    ],
  },

  // ── Sensors ─────────────────────────────────────────────────────────────────
  {
    sku: 'SENSOR_IMU_BNO055',
    name: 'BNO055 9-DoF IMU Module',
    category: 'sensor',
    description: '9-DOF IMU with on-chip sensor fusion. I2C/UART. Outputs calibrated quaternion/Euler. For robot orientation and stabilization.',
    tags: ['sensor', 'imu', 'orientation', 'gyro', 'accelerometer', 'magnetometer', 'i2c', 'fusion'],
    supplier: 'Adafruit / Generic',
    price_usd: 12.00,
    lead_time_days: 7,
    mesh_url: 'stl/esp32_s3_dev.stl',
    cad_url: null,
    specs: { weight_g: 3, interface: 'i2c', sample_rate_hz: 100, dims_mm: [20, 27, 4] },
    mount_points: [
      { id: 'board_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_generic', is_joint: false },
    ],
  },
  {
    sku: 'SENSOR_TOF_VL53L0X',
    name: 'VL53L0X Time-of-Flight Sensor',
    category: 'sensor',
    description: 'ToF ranging sensor up to 2m, I2C. ±3% accuracy. Detects obstacles for mobile robots or end-effector distance sensing.',
    tags: ['sensor', 'tof', 'distance', 'ranging', 'obstacle', 'i2c', 'proximity'],
    supplier: 'STMicroelectronics / Adafruit',
    price_usd: 5.00,
    lead_time_days: 7,
    mesh_url: 'stl/esp32_s3_dev.stl',
    cad_url: null,
    specs: { weight_g: 2, interface: 'i2c', range_mm: 2000, dims_mm: [13, 18, 5] },
    mount_points: [
      { id: 'board_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_generic', is_joint: false },
    ],
  },
  {
    sku: 'SENSOR_CAMERA_OV2640',
    name: 'OV2640 2MP Camera Module',
    category: 'sensor',
    description: '2MP CMOS camera with flexible cable. Used on ESP32-CAM for object detection or manipulation feedback.',
    tags: ['sensor', 'camera', 'vision', 'ov2640', '2mp', 'esp32-cam', 'object-detection'],
    supplier: 'Generic',
    price_usd: 8.00,
    lead_time_days: 7,
    mesh_url: 'stl/esp32_s3_dev.stl',
    cad_url: null,
    specs: { weight_g: 5, interface: 'dvp', resolution: '1600×1200', fov_deg: 66, dims_mm: [24, 24, 6] },
    mount_points: [
      { id: 'board_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_generic', is_joint: false },
    ],
  },
  {
    sku: 'SENSOR_DEPTH_D435I',
    name: 'Intel RealSense D435i Depth Camera',
    category: 'sensor',
    description: 'Stereo depth camera, 30fps 1280×720 depth. Integrated IMU. For 3D scene understanding and manipulation.',
    tags: ['sensor', 'depth', 'stereo', 'realsense', 'intel', '3d', 'rgb-d', 'manipulation', 'ros2'],
    supplier: 'Intel',
    price_usd: 197.00,
    lead_time_days: 14,
    mesh_url: 'stl/esp32_s3_dev.stl',
    cad_url: null,
    specs: { weight_g: 72, interface: 'usb-3', range_mm: 10000, dims_mm: [90, 25, 25] },
    mount_points: [
      { id: 'board_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_generic', is_joint: false },
    ],
  },
  {
    sku: 'SENSOR_LIDAR_LD14P',
    name: 'LD14P 360° LiDAR (12m)',
    category: 'sensor',
    description: '360° single-plane LiDAR, 12m range, 4500 points/rev. UART output. For SLAM-based navigation on mobile robots.',
    tags: ['sensor', 'lidar', '360', 'slam', 'navigation', 'mobile', 'mapping', 'uart'],
    supplier: 'LDROBOT',
    price_usd: 35.00,
    lead_time_days: 10,
    mesh_url: 'stl/esp32_s3_dev.stl',
    cad_url: null,
    specs: { weight_g: 98, interface: 'uart', range_m: 12, scan_rate_hz: 10, dims_mm: [97, 97, 38] },
    mount_points: [
      { id: 'board_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_generic', is_joint: false },
    ],
  },
  {
    sku: 'SENSOR_FORCE_50N',
    name: 'Force/Torque Sensor 50N',
    category: 'sensor',
    description: 'Miniature load cell, 50N max, I2C readout. Mounts between wrist and gripper for grasp force feedback.',
    tags: ['sensor', 'force', 'torque', 'load-cell', 'grasp', 'feedback', 'i2c', 'wrist'],
    supplier: '1688 generic',
    price_usd: 22.00,
    lead_time_days: 12,
    mesh_url: 'stl/esp32_s3_dev.stl',
    cad_url: null,
    specs: { weight_g: 15, interface: 'i2c', max_force_n: 50, dims_mm: [30, 30, 8] },
    mount_points: [
      { id: 'robot_side', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
      { id: 'gripper_side', position: [0, 0, 8], orientation: [0, 0, 0, 1], connector: 'm3_4hole_20x20', is_joint: false },
    ],
  },

  // ── Motors ───────────────────────────────────────────────────────────────────
  {
    sku: 'MOTOR_DC_25GA370',
    name: 'DC Gearmotor 25GA-370 (200 RPM)',
    category: 'motor',
    description: '12V DC gearmotor with 6mm D-shaft output, 200 RPM at 12V. Compact 25mm barrel. For small wheeled robot drive train.',
    tags: ['motor', 'dc', 'gearmotor', '12v', 'wheeled', 'mobile', 'drive', 'd-shaft'],
    supplier: 'Generic / Aliexpress',
    price_usd: 6.50,
    lead_time_days: 12,
    mesh_url: 'stl/feetech_sts3215.stl',
    cad_url: null,
    specs: { weight_g: 70, voltage_v: 12.0, max_rpm: 200, torque_nm: 0.49, shaft_mm: 6, dims_mm: [25, 25, 75] },
    mount_points: [
      { id: 'body_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_generic', is_joint: false },
      { id: 'shaft', position: [0, 0, 75], orientation: [0, 0, 0, 1], connector: 'shaft_d_6mm', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-36000, 36000] },
    ],
  },
  {
    sku: 'MOTOR_DC_37GA520',
    name: 'DC Gearmotor 37GA-520 (100 RPM)',
    category: 'motor',
    description: '12V DC gearmotor with 6mm D-shaft, 100 RPM, 37mm barrel. Higher torque for heavier mobile platforms.',
    tags: ['motor', 'dc', 'gearmotor', '12v', 'wheeled', 'mobile', 'heavy', 'd-shaft', 'high-torque'],
    supplier: 'Generic / Aliexpress',
    price_usd: 9.00,
    lead_time_days: 12,
    mesh_url: 'stl/feetech_sts3215.stl',
    cad_url: null,
    specs: { weight_g: 180, voltage_v: 12.0, max_rpm: 100, torque_nm: 1.2, shaft_mm: 6, dims_mm: [37, 37, 100] },
    mount_points: [
      { id: 'body_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_generic', is_joint: false },
      { id: 'shaft', position: [0, 0, 100], orientation: [0, 0, 0, 1], connector: 'shaft_d_6mm', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-36000, 36000] },
    ],
  },
  {
    sku: 'MOTOR_NEMA17_STEPPER',
    name: 'NEMA 17 Stepper Motor (40mm)',
    category: 'motor',
    description: '1.7A bipolar stepper, 40mm body length, 5mm D-shaft. 1.8°/step. For precise linear axes and joints needing holding torque.',
    tags: ['motor', 'stepper', 'nema17', '1.8deg', 'linear', 'precise', 'cnc', 'arm'],
    supplier: 'Generic / Aliexpress',
    price_usd: 8.00,
    lead_time_days: 10,
    mesh_url: 'stl/feetech_sts3215.stl',
    cad_url: null,
    specs: { weight_g: 280, voltage_v: 12.0, torque_nm: 0.46, current_a: 1.7, step_deg: 1.8, shaft_mm: 5, dims_mm: [42, 42, 40] },
    mount_points: [
      { id: 'face_mount', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'm3_4hole_30x30', is_joint: false },
      { id: 'shaft', position: [21, 21, 45], orientation: [0, 0, 0, 1], connector: 'shaft_d_5mm', is_joint: true, joint_axis: [0, 0, 1], joint_limits_deg: [-36000, 36000] },
    ],
  },

  // ── Wheels ───────────────────────────────────────────────────────────────────
  {
    sku: 'WHEEL_MECANUM_75MM',
    name: 'Mecanum Wheel 75mm (Left)',
    category: 'wheel',
    description: '75mm aluminum mecanum wheel, left-hand roller pattern. 6mm D-shaft bore. For 4-wheel holonomic drive platforms.',
    tags: ['wheel', 'mecanum', '75mm', 'holonomic', 'omnidirectional', 'mobile', 'd-shaft'],
    supplier: 'Generic / Aliexpress',
    price_usd: 8.50,
    lead_time_days: 12,
    mesh_url: 'stl/bracket_u_small.stl',
    cad_url: null,
    specs: { weight_g: 80, diameter_mm: 75, width_mm: 38, bore_mm: 6, dims_mm: [75, 75, 38] },
    mount_points: [
      { id: 'hub', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'shaft_d_6mm', is_joint: false },
    ],
  },
  {
    sku: 'WHEEL_MECANUM_100MM',
    name: 'Mecanum Wheel 100mm (Left)',
    category: 'wheel',
    description: '100mm mecanum wheel, left-hand pattern. 6mm D-shaft bore. For larger holonomic platforms up to 10kg payload.',
    tags: ['wheel', 'mecanum', '100mm', 'holonomic', 'omnidirectional', 'mobile', 'large'],
    supplier: 'Generic / Aliexpress',
    price_usd: 15.00,
    lead_time_days: 12,
    mesh_url: 'stl/bracket_u_small.stl',
    cad_url: null,
    specs: { weight_g: 180, diameter_mm: 100, width_mm: 50, bore_mm: 6, dims_mm: [100, 100, 50] },
    mount_points: [
      { id: 'hub', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'shaft_d_6mm', is_joint: false },
    ],
  },
  {
    sku: 'WHEEL_RUBBER_65MM',
    name: 'Rubber Wheel 65mm',
    category: 'wheel',
    description: 'Rubber-tyred wheel 65mm diameter, 26mm wide. 6mm D-shaft bore. For two-wheel differential drive robots.',
    tags: ['wheel', 'rubber', '65mm', 'differential', 'drive', 'mobile', 'd-shaft', 'traction'],
    supplier: 'Generic / Aliexpress',
    price_usd: 3.50,
    lead_time_days: 10,
    mesh_url: 'stl/bracket_u_small.stl',
    cad_url: null,
    specs: { weight_g: 40, diameter_mm: 65, width_mm: 26, bore_mm: 6, dims_mm: [65, 65, 26] },
    mount_points: [
      { id: 'hub', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'shaft_d_6mm', is_joint: false },
    ],
  },
  {
    sku: 'WHEEL_OMNI_60MM',
    name: 'Omni Wheel 60mm (4-roller)',
    category: 'wheel',
    description: '60mm omni wheel with 4 passive rollers. 6mm D-shaft. Used as caster or in 3-wheel omni drive configurations.',
    tags: ['wheel', 'omni', '60mm', 'caster', 'omnidirectional', 'passive', 'd-shaft'],
    supplier: 'Generic / Aliexpress',
    price_usd: 5.50,
    lead_time_days: 10,
    mesh_url: 'stl/bracket_u_small.stl',
    cad_url: null,
    specs: { weight_g: 35, diameter_mm: 60, width_mm: 20, bore_mm: 6, dims_mm: [60, 60, 20] },
    mount_points: [
      { id: 'hub', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'shaft_d_6mm', is_joint: false },
    ],
  },

  // ── Additional Grippers ──────────────────────────────────────────────────────
  {
    sku: 'GRIPPER_SERVO_CLAW_50MM',
    name: 'Servo Claw Gripper 50mm',
    category: 'gripper',
    description: 'Single-servo claw gripper, 50mm open span. Driven by one 25T servo horn. Lightweight plastic. Good for pick-and-place of small objects.',
    tags: ['gripper', 'claw', 'single-servo', 'end-effector', 'plastic', 'lightweight', 'pick-place'],
    supplier: '1688 generic',
    price_usd: 9.00,
    lead_time_days: 10,
    mesh_url: 'stl/gripper_parallel_mini.stl',
    cad_url: null,
    specs: { weight_g: 25, max_payload_g: 150, stroke_mm: 50, dims_mm: [55, 25, 55] },
    mount_points: [
      { id: 'servo_input', position: [0, 0, 0], orientation: [0, 0, 0, 1], connector: 'servo_horn_25T', is_joint: false },
      { id: 'wrist_mount', position: [0, 0, 55], orientation: [0, 0, 1, 0], connector: 'm3_4hole_20x20', is_joint: false },
    ],
  },
  {
    sku: 'GRIPPER_MAGNETIC_12V',
    name: 'Electromagnetic Gripper 12V (2kg)',
    category: 'gripper',
    description: '12V DC electromagnet, 2kg holding force. On/off only. For sorting ferrous objects. No moving parts.',
    tags: ['gripper', 'electromagnet', 'magnetic', '12v', 'sorting', 'ferrous', 'no-moving-parts'],
    supplier: 'Generic / Aliexpress',
    price_usd: 12.00,
    lead_time_days: 12,
    mesh_url: 'stl/gripper_parallel_mini.stl',
    cad_url: null,
    specs: { weight_g: 120, holding_kg: 2.0, voltage_v: 12.0, dims_mm: [30, 30, 25] },
    mount_points: [
      { id: 'wrist_mount', position: [0, 0, 25], orientation: [0, 0, 1, 0], connector: 'm3_4hole_20x20', is_joint: false },
    ],
  },
];

export function searchCatalogue(
  query: string | null,
  category: string | null,
  maxResults = 10,
): Part[] {
  let results = CATALOGUE;
  if (category) {
    results = results.filter((p) => p.category === category);
  }
  if (query) {
    const q = query.toLowerCase();
    results = results.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        p.description.toLowerCase().includes(q) ||
        p.sku.toLowerCase().includes(q) ||
        p.tags.some((t) => t.toLowerCase().includes(q)),
    );
  }
  return results.slice(0, maxResults);
}

export function getCataloguePart(sku: string): Part | null {
  return CATALOGUE.find((p) => p.sku === sku) ?? null;
}
